In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr+2

array([3, 4, 5, 6])

Numpy vs List

'''
list vs numpy diffrence is numpy takes 
less time as compared to list 

'''

In [5]:
py_list=[1,2,3,4,5]
print("Python list multiplication is: ",py_list*2)  #append value two times

np_array=np.array([1,2,3,4,5])
print("Numpy array multiplication is: ",np_array*2)  #multiply items value by 2(scaler)


Python list multiplication is:  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Numpy array multiplication is:  [ 2  4  6  8 10]


find min and max 

In [ ]:
import numpy as np
arr=np.random.rand(1,5)
print(arr)
print("maximum value in this array is:",arr.max())
print("Index of max value is",np.where(arr==arr.max())) #gives row col form output because arr is multi dimensional
# print(arr.argmax()) tells about index of maximum value used when search based on condition

# sort array
print("Sorted array is:",np.sort(arr))
des_arr=np.sort(arr,axis=1)[:, ::-1]
print("Descending sorting is :",des_arr)

# unique element
arr=np.array([1,2,1,2,3,4,4,5,5])
print("All occured element is:",np.unique(arr)) #sort result and print one occurence of every num in arr
uniq,count=np.unique(arr,return_counts=True)
uniq_ele=uniq[count==1]
print("Unique element is:",uniq_ele)
ans=np.array([[uniq],[count]])
print("count is:",ans)

Number in range 

In [ ]:
arr=np.arange(10,51,5)
print("Number from 10 to 50 with step 5 is: ",arr)

matrix=np.ones((5,5))
print("Identity matrix is: ",matrix)
print("Shape of identity matrix is: ",matrix.shape)
print("Number of element in matrix is: ",matrix.size)
print("Data type of element in matrix is: ",matrix.dtype)


Reshap a matrix

In [ ]:
import numpy as np

# reshape array of size 12 into matrix of 3,4 and then 4,3
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr2=arr.reshape(3,4)
print("reshaped array is:",arr2)
print("Flatten array is",arr2.flatten())

# extract first 3 element fromm array
extract=arr[0:3]
print("Extracted elemet is: ",extract)

# extract last row from 2d array 
extract=arr2[2:]
print("Extracted last row from 2d array: ",extract)

# addd two 2d array
arr3=arr2.copy()
add_arr=np.add(arr2,arr3)
print("Sum of arr2 and arr3 is: ",add_arr)

# multiply array by scaler value
mul=arr2*3
print("Multiplied by scaler value 3:",mul)

# multiple each element
mul=np.multiply(arr2,arr3)
print("Multiplied each element of arr1 and arr2 :",mul)

# replace all value greater than 10 with 0
new_arr=np.where(arr>10,0,arr)
print("replaced array is:",new_arr)


data operation 

In [ ]:
import numpy as np

# data=[resturant_id,2021,2022,2023,2024]
sales_data=np.array([
    [1,1500,2000,2200,2500],
    [2,1000,1800,1400,2300],
    [3,2300,2000,2400,1200],
    [4,1600,1850,2050,1300],
    [5,1350,1240,1100,1600]
])

print("====Zomato sales analysis===")
print("\nShape of sales data is:",sales_data.shape)
print("\n Sample data of first 3 restaurant is: ",sales_data[:3])
print("\nSales data except restaurant id is: ",sales_data[:,1:])

print("\nTotal sales per year is :",np.sum(sales_data,axis=0))
print("\nYearly sales is :",np.sum(sales_data[: ,1:],axis=0)) #axis =0 means col and axis=1 means row

print("\nTotal Sales of a company in 5 year is :",np.sum(sales_data[: ,1:],axis=1))

print("\nMinimum sales per restaurant is: ",np.min(sales_data[: ,1:],axis=1))
print("\nMaximum sales per restaurant is :",np.max(sales_data[: ,1:],axis=1))
print("\nMaximum sales per year is: ",np.max(sales_data[: ,1:],axis=0))

print("\n Average sales per restaurant is: ",np.average(sales_data[: ,1:],axis=1))

# cumulative sales sum of all previous one based on axis either row or col as axis=0 or 1
print("Cumulative sales is: ",np.cumsum(sales_data[: ,1:],axis=1))



1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.

In [6]:
list1=[1,2,3,4,5]
arr_1d=np.array(list1)
arr_1d

array([1, 2, 3, 4, 5])

2. Create a 3x3 matrix with values ranging from 2 to 10.

In [7]:
matrix=np.arange(2,11)
matrix.reshape(3,3)
matrix

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [8]:
vector1=np.zeros(10)
vector1[6]=11
vector1

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

4. Write a Python program to reverse an array (first element becomes last).

In [9]:
arr=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
rev=arr[: :-1]
rev

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [10]:
arr=np.ones((5,5))
arr[1:4,1:4]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

6. Write a Python program to add a border (filled with 0's) around an existing array.

In [11]:
arr=np.ones((3,3))
padded=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
padded

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:

In [12]:
checkBoard=np.zeros((8,8))
checkBoard[::2,1::2]=1
checkBoard[1::2, ::2]=1
print(checkBoard)
# or another way
checkboard2=np.indices((8,8)).sum(axis=0)%2
checkboard2

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

8. Write a Python program to convert a list and tuple into arrays.

In [13]:
list1=[1,2,3,4,5]
arr_1d=np.array(list1)
print(arr_1d)

tup=((1,2,3,4,5),(6,7,8,9,0))
print(np.array(tup))


[1 2 3 4 5]
[[1 2 3 4 5]
 [6 7 8 9 0]]


9.  Write a Python program to append values to the end of an array.

In [14]:
arr=np.array([1,2,3,4])
new_arr=np.append(arr,([5,6,7,8,9]))
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

10. Write a Python program to find the real and imaginary parts of an array of complex

In [15]:
arr=np.array([ 1.00000000+0.j ,0.70710678+0.70710678j])
print(np.real(arr))
print(np.imag(arr))

[1.         0.70710678]
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [16]:
arr=np.array([1,2,3,4,5,6])
print("Number of element in array is: ",arr.size)
print("length of one element in bytes is: ",arr.itemsize)
print("total byte consumed by element is: ",arr.nbytes)

Number of element in array is:  6
length of one element in bytes is:  8
total byte consumed by element is:  48


Write a Python program to find common values between two arrays.

In [17]:
arr=np.array([1,2,3,4,5])
arr2=np.array([2,4,7,8,9])
print("Common element is: ",np.intersect1d(arr,arr2))


Common element is:  [2 4]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [18]:
arr=np.array([11,2,3,4,5])
arr2=np.array([2,4,7,8,9])
diff=np.setdiff1d(arr,arr2)
print("Element in first array and not in second is: ",np.sort(diff))

Element in first array and not in second is:  [ 3  5 11]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [19]:
arr=np.array([0,10,20,40,60,80])
arr2=np.array([10,30,40,50,70])
diff=np.setdiff1d(arr,arr2)
diff2=np.setdiff1d(arr2,arr)
ans=np.append(diff,diff2)
print("Excluive or of two arrays is: ",np.sort(ans))

Excluive or of two arrays is:  [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.

In [20]:
arr=np.array([1,2])
arr2=np.array([2,4])

print(arr>arr2)
print(arr>=arr2)
print(arr<arr2)
print(arr<=arr2)


[False False]
[False False]
[ True  True]
[ True  True]


Write a Python program to save a NumPy array to a text file.

In [21]:
arr=np.array([1,2,3,4,5])
np.savetxt('array.txt',arr,fmt='%d' ,delimiter=',')
print("data saved to array.txt")



data saved to array.txt


Write a Python program to create a contiguous flattened array.

In [22]:
arr=np.array([[1,2],[3,4]])

flattened=arr.flatten()
print("Flattened array is: ",flattened)

Flattened array is:  [1 2 3 4]


Write a Python program to change the data type of an array.

In [23]:
arr=np.array([[ 2,4,6],[6,8,10]])
print("Datatype of array is: ",arr.dtype)
arr=arr.astype(np.float64)
print("Changed Datatype of array is: ",arr.dtype)


Datatype of array is:  int64
Changed Datatype of array is:  float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [24]:
arr=np.array([1,1,1])
ans=np.diag(arr)
print(ans)
# diag is to create diagonal and to see diagonal used arr.diagonal and sum of diagonal use tace

[[1 0 0]
 [0 1 0]
 [0 0 1]]


19. Write a Python program to create an array which looks like below array.

In [25]:
arr=np.zeros((4,3))
for i in range(1,4):
    for j in range(min(i,4)):
        arr[i][j]=1
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.

In [26]:
arr2_d=np.array([[0, 1, 3], [5, 7, 9]])
arr2d_2=np.array([[0, 2, 4], [6, 8, 10]])
print(np.hstack((arr2_d,arr2d_2)))

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).

In [30]:
arr=np.array([1,2,3,4,5])
arr.flags.writeable=False
arr[0]=2
arr

ValueError: assignment destination is read-only

22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.

In [37]:
arr=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
arr
element=3
print(arr*element)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.

In [38]:
arr=np.array([[1,2],[3,4],[5,6]])
ls=arr.tolist()
ls

[[1, 2], [3, 4], [5, 6]]

24. Write a Python program to convert a NumPy array into Python list structure.

In [41]:
arr=np.array([ 0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349,0.35399976,0.99469633,0.0694458,0.54711478])
arr1=np.round(arr,3)
ls=arr1.tolist()
ls


[0.262, 0.528, 0.572, 0.593, 0.783, 0.697, 0.354, 0.995, 0.069, 0.547]

25. Write a Python program to suppresses the use of scientific notation for small

In [42]:
arr=np.array([ 1.60000000e-10,1.60000000e+00,1.20000000e+03,2.35000000e-01])
arr1=np.round(arr,3)
print(arr1.tolist())

[0.0, 1.6, 1200.0, 0.235]


26. Write a Python program to how to add an extra column to an numpy array.

In [52]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
col=np.array([6,7])
ans=np.column_stack((arr,col))
ans

array([[1, 2, 3, 4, 6],
       [5, 6, 7, 8, 7]])

27. Write a Python program to remove specific elements in a numpy array.

In [55]:
arr=np.array([ 10,20,30,40,50,60,70,80,90,100])
deleted=np.delete(arr,[0,3,4])
deleted

array([ 20,  30,  60,  70,  80,  90, 100])